# Generated by Django 5.1.2 on 2024-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Healthapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(max_length=100),
        ),
    ]
