# Generated by Django 5.1.2 on 2024-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Healthapp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
